### ISSUE TITLE
Fast Clock Ratio

### ISSUE THREAD

**Issue by DarkTerritory** [ekapus/TrainCrew#8]
Took a look at your app, very nice, good idea. I'd like to suggest that you include a options tab to include some variables to customize the program, particularly the fast clock ratio. Not everyone uses a 4:1 ratio and it would be great to be able to set this to the layout's standard. 

Great work!

**Comment by ekapus** [comment]
That was a really good idea. 
I've made an update recently that puts that setting in a configuration file. 
https://github.com/ekapus/TrainCrew/blob/master/js/config.js

In order to use the setting though, you need to download the app, change the value,  and host it yourself somewhere. That shouldn't be hard because the entire thing is all flat HTML for that very reason.
